name: Schedule

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: sh
              run: sh server_check.sh
